/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef ABSYN_HEADER
#define ABSYN_HEADER

/* strdup was not in the ISO C standard before 6/2019 (C2x), but in POSIX 1003.1.
 * See: https://en.cppreference.com/w/c/experimental/dynamic/strdup
 * Setting _POSIX_C_SOURCE to 200809L activates strdup in string.h.
 */
#define _POSIX_C_SOURCE 200809L

#include <stddef.h>  /* NULL */
#include <string.h>  /* strdup */

/* C++ Abstract Syntax Interface.*/

/********************   TypeDef Section    ********************/

typedef int Integer;
typedef char Char;
typedef double Double;
typedef char* String;
typedef char* Ident;

/********************   Forward Declarations    ***********************/
struct Expr_;
typedef struct Expr_ *Expr;

struct Binop_;
typedef struct Binop_ *Binop;

/********************   Abstract Syntax Classes    ********************/

struct Expr_
{
  enum { is_EVar, is_ETrue, is_EFalse, is_EInt, is_EBinOp } kind;
  union
  {
    struct { Ident ident_; } eVar_;
    struct { Integer integer_; } eInt_;
    struct { Binop binop_; Expr expr_1, expr_2; } eBinOp_;
  } u;
};

Expr make_EVar(Ident p0);
Expr make_ETrue(void);
Expr make_EFalse(void);
Expr make_EInt(Integer p0);
Expr make_EBinOp(Expr p0, Binop p1, Expr p2);

struct Binop_
{
  enum { is_Add, is_Sub, is_Eq, is_Lt, is_And } kind;
  union
  {
  } u;
};

Binop make_Add(void);
Binop make_Sub(void);
Binop make_Eq(void);
Binop make_Lt(void);
Binop make_And(void);

/***************************   Cloning   ******************************/

Expr clone_Expr(Expr p);
Binop clone_Binop(Binop p);

/********************   Recursive Destructors    **********************/

/* These free an entire abstract syntax tree
 * including all subtrees and strings.
 *
 * Will not work properly if there is sharing in the tree,
 * i.e., when some pointers are aliased.  In this case
 * it will attempt to free the same memory twice.
 */

void free_Expr(Expr p);
void free_Binop(Binop p);


#endif
