/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/* C Abstract Syntax Implementation. */

#include <stdio.h>
#include <stdlib.h>
#include "Absyn.h"

/********************   EVar    ********************/

Expr make_EVar(Ident p1)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EVar!\n");
        exit(1);
    }
    tmp->kind = is_EVar;
    tmp->u.eVar_.ident_ = p1;
    return tmp;
}

/********************   ETrue    ********************/

Expr make_ETrue()
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ETrue!\n");
        exit(1);
    }
    tmp->kind = is_ETrue;
    return tmp;
}

/********************   EFalse    ********************/

Expr make_EFalse()
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EFalse!\n");
        exit(1);
    }
    tmp->kind = is_EFalse;
    return tmp;
}

/********************   EInt    ********************/

Expr make_EInt(Integer p1)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EInt!\n");
        exit(1);
    }
    tmp->kind = is_EInt;
    tmp->u.eInt_.integer_ = p1;
    return tmp;
}

/********************   EBinOp    ********************/

Expr make_EBinOp(Expr p1, Binop p2, Expr p3)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EBinOp!\n");
        exit(1);
    }
    tmp->kind = is_EBinOp;
    tmp->u.eBinOp_.expr_1 = p1;
    tmp->u.eBinOp_.binop_ = p2;
    tmp->u.eBinOp_.expr_2 = p3;
    return tmp;
}

/********************   Add    ********************/

Binop make_Add()
{
    Binop tmp = (Binop) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Add!\n");
        exit(1);
    }
    tmp->kind = is_Add;
    return tmp;
}

/********************   Sub    ********************/

Binop make_Sub()
{
    Binop tmp = (Binop) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Sub!\n");
        exit(1);
    }
    tmp->kind = is_Sub;
    return tmp;
}

/********************   Eq    ********************/

Binop make_Eq()
{
    Binop tmp = (Binop) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Eq!\n");
        exit(1);
    }
    tmp->kind = is_Eq;
    return tmp;
}

/********************   Lt    ********************/

Binop make_Lt()
{
    Binop tmp = (Binop) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Lt!\n");
        exit(1);
    }
    tmp->kind = is_Lt;
    return tmp;
}

/********************   And    ********************/

Binop make_And()
{
    Binop tmp = (Binop) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating And!\n");
        exit(1);
    }
    tmp->kind = is_And;
    return tmp;
}

/***************************   Cloning   ******************************/

Expr clone_Expr(Expr p)
{
  switch(p->kind)
  {
  case is_EVar:
    return make_EVar (strdup(p->u.eVar_.ident_));

  case is_ETrue:
    return make_ETrue ();

  case is_EFalse:
    return make_EFalse ();

  case is_EInt:
    return make_EInt (p->u.eInt_.integer_);

  case is_EBinOp:
    return make_EBinOp
      ( clone_Expr(p->u.eBinOp_.expr_1)
      , clone_Binop(p->u.eBinOp_.binop_)
      , clone_Expr(p->u.eBinOp_.expr_2)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning Expr!\n");
    exit(1);
  }
}

Binop clone_Binop(Binop p)
{
  switch(p->kind)
  {
  case is_Add:
    return make_Add ();

  case is_Sub:
    return make_Sub ();

  case is_Eq:
    return make_Eq ();

  case is_Lt:
    return make_Lt ();

  case is_And:
    return make_And ();

  default:
    fprintf(stderr, "Error: bad kind field when cloning Binop!\n");
    exit(1);
  }
}

/********************   Recursive Destructors    **********************/

/* These free an entire abstract syntax tree
 * including all subtrees and strings.
 *
 * Will not work properly if there is sharing in the tree,
 * i.e., when some pointers are aliased.  In this case
 * it will attempt to free the same memory twice.
 */

void free_Expr(Expr p)
{
  switch(p->kind)
  {
  case is_EVar:
    free(p->u.eVar_.ident_);
    break;

  case is_ETrue:
    break;

  case is_EFalse:
    break;

  case is_EInt:
    break;

  case is_EBinOp:
    free_Expr(p->u.eBinOp_.expr_1);
    free_Binop(p->u.eBinOp_.binop_);
    free_Expr(p->u.eBinOp_.expr_2);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing Expr!\n");
    exit(1);
  }
  free(p);
}

void free_Binop(Binop p)
{
  switch(p->kind)
  {
  case is_Add:
    break;

  case is_Sub:
    break;

  case is_Eq:
    break;

  case is_Lt:
    break;

  case is_And:
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing Binop!\n");
    exit(1);
  }
  free(p);
}

