/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"

Expr  pExpr(FILE *inp);
Expr psExpr(const char *str);
Binop  pBinop(FILE *inp);
Binop psBinop(const char *str);

#endif
