/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitExpr(Expr p)
{
  switch(p->kind)
  {
  case is_EVar:
    /* Code for EVar Goes Here */
    visitIdent(p->u.eVar_.ident_);
    break;
  case is_ETrue:
    /* Code for ETrue Goes Here */
    break;
  case is_EFalse:
    /* Code for EFalse Goes Here */
    break;
  case is_EInt:
    /* Code for EInt Goes Here */
    visitInteger(p->u.eInt_.integer_);
    break;
  case is_EBinOp:
    /* Code for EBinOp Goes Here */
    visitExpr(p->u.eBinOp_.expr_1);
    visitBinop(p->u.eBinOp_.binop_);
    visitExpr(p->u.eBinOp_.expr_2);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Expr!\n");
    exit(1);
  }
}

void visitBinop(Binop p)
{
  switch(p->kind)
  {
  case is_Add:
    /* Code for Add Goes Here */
    break;
  case is_Sub:
    /* Code for Sub Goes Here */
    break;
  case is_Eq:
    /* Code for Eq Goes Here */
    break;
  case is_Lt:
    /* Code for Lt Goes Here */
    break;
  case is_And:
    /* Code for And Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Binop!\n");
    exit(1);
  }
}

void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

