/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printExpr(Expr p)
{
  _n_ = 0;
  bufReset();
  ppExpr(p, 0);
  return buf_;
}
char *printBinop(Binop p)
{
  _n_ = 0;
  bufReset();
  ppBinop(p, 0);
  return buf_;
}
char *showExpr(Expr p)
{
  _n_ = 0;
  bufReset();
  shExpr(p);
  return buf_;
}
char *showBinop(Binop p)
{
  _n_ = 0;
  bufReset();
  shBinop(p);
  return buf_;
}
void ppExpr(Expr p, int _i_)
{
  switch(p->kind)
  {
  case is_EVar:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.eVar_.ident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ETrue:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("true");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EFalse:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("false");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EInt:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.eInt_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EBinOp:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExpr(p->u.eBinOp_.expr_1, 0);
    ppBinop(p->u.eBinOp_.binop_, 0);
    ppExpr(p->u.eBinOp_.expr_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Expr!\n");
    exit(1);
  }
}

void ppBinop(Binop p, int _i_)
{
  switch(p->kind)
  {
  case is_Add:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('+');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Sub:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('-');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Eq:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("==");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Lt:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_And:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("&&");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Binop!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void shExpr(Expr p)
{
  switch(p->kind)
  {
  case is_EVar:
    bufAppendC('(');

    bufAppendS("EVar");

    bufAppendC(' ');

    shIdent(p->u.eVar_.ident_);

    bufAppendC(')');

    break;
  case is_ETrue:

    bufAppendS("ETrue");




    break;
  case is_EFalse:

    bufAppendS("EFalse");




    break;
  case is_EInt:
    bufAppendC('(');

    bufAppendS("EInt");

    bufAppendC(' ');

    shInteger(p->u.eInt_.integer_);

    bufAppendC(')');

    break;
  case is_EBinOp:
    bufAppendC('(');

    bufAppendS("EBinOp");

    bufAppendC(' ');

    shExpr(p->u.eBinOp_.expr_1);
  bufAppendC(' ');
    shBinop(p->u.eBinOp_.binop_);
  bufAppendC(' ');
    shExpr(p->u.eBinOp_.expr_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Expr!\n");
    exit(1);
  }
}

void shBinop(Binop p)
{
  switch(p->kind)
  {
  case is_Add:

    bufAppendS("Add");




    break;
  case is_Sub:

    bufAppendS("Sub");




    break;
  case is_Eq:

    bufAppendS("Eq");




    break;
  case is_Lt:

    bufAppendS("Lt");




    break;
  case is_And:

    bufAppendS("And");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Binop!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

